### ISSUE TITLE
Invoke-RancherApi not found as Cmdlet

### ISSUE THREAD

**Issue by ThomasWilla** [nicholasdille/PowerShell-Rancher#1]
PS PSlib:\> Get-RancherHost
Invoke-RancherApi : Die Benennung "Invoke-RancherApi" wurde nicht als Name eines Cmdlet, einer Funktion, einer
Skriptdatei oder eines ausführbaren Programms erkannt. Überprüfen Sie die Schreibweise des Namens, oder ob der Pfad
korrekt ist (sofern enthalten), und wiederholen Sie den Vorgang.
In C:\Program Files\WindowsPowerShell\Modules\Rancher\0.1.19\Functions\Public\Get-RancherHost.ps1:29 Zeichen:14
+     $Hosts = Invoke-RancherApi -Path '/hosts'
+              ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Invoke-RancherApi:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by nicholasdille** [comment]
I fear, you issue is caused by the fact that I have not created a documentation yet. Can you please test the following:

```powershell
Install-Module -Name Helpers,WebRequest,Rancher -AllowClobber -Force
Import-Module -Name Helpers,WebRequest,Rancher -Force
Set-RancherServer -Server https://your_rancher_here.com -AccessKey your_access_key_here -SecretKey your_secret_key_here
Get-RancherHost
```

You will only see hosts from environment available to the specified API key pair.

I have isolated some functionality in separate modules. `Helpers` provides (among other) cmdlets to encode in base64 which is required for basic authentication. `WebRequest` provides (among other) basic authentication for `Invoke-WebRequest`. The `-AllowClobber` is required in `Install-Module` because `WebRequest` overrides `Invoke-WebRequest` and `Invoke-RestMethod`.

**Comment by ThomasWilla** [comment]
Yes, now it works and I can connect to my Rancher Farm and get all Information. Thank you great Module!

**Comment by nicholasdille** [comment]
I added some documentation to make sure this doesn't happen again
